### ISSUE TITLE
Add contains_point method to Triangle struct

### ISSUE THREAD

**Issue by semigrp** [nash1111/delauny_creator#3]
Description:
Currently, the Triangle struct in delaunay_creator does not have a contains_point method to determine if a given point is inside the triangle. This functionality can be useful in various applications, particularly in graphics or fractal drawing.

Proposed changes:
Please add a contains_point method to the Triangle struct. This method should determine whether a given Point2D is inside the triangle or not.

**Comment by nash1111** [comment]
Thanks for the suggestion!
I decided not to create a function to determine if a triangle contains a point based on the following two points

1. Bowyer-Watson algorithm does not need to determine if a point is inside a triangle.
2. I want to minimize the number of functions by adding functions each time it becomes necessary.

**Comment by semigrp** [comment]
Please close.
